import * as React from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';
import MenuItem from '@mui/material/MenuItem';
import TextField from '@mui/material/TextField';
import Checkbox from '@mui/material/Checkbox';
import FormControlLabel from '@mui/material/FormControlLabel';
import Divider from '@mui/material/Divider';
import Stack from '@mui/material/Stack';
import Chip from '@mui/material/Chip';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import DownloadIcon from '@mui/icons-material/Download';
import PrintIcon from '@mui/icons-material/Print';
import DescriptionIcon from '@mui/icons-material/Description';
import AssessmentIcon from '@mui/icons-material/Assessment';

interface Target {
  id: number;
  profileId: string;
  name: string;
  type: string;
  host: string;
}

interface Profile {
  id: string;
  name: string;
}

export default function ReportsTab() {
  const [profiles, setProfiles] = React.useState<Profile[]>([]);
  const [targets, setTargets] = React.useState<Target[]>([]);

  // Form State
  const [scope, setScope] = React.useState<'profile' | 'target'>('profile');
  const [selectedProfileId, setSelectedProfileId] = React.useState<string>('');
  const [selectedTargetId, setSelectedTargetId] = React.useState<string>('all');
  const [fromDate, setFromDate] = React.useState('2026-07-27');
  const [toDate, setToDate] = React.useState('2026-08-10');
  const [reportTitle, setReportTitle] = React.useState('Monthly Infrastructure SLA & Outage Report');
  const [authorNotes, setAuthorNotes] = React.useState('Executive summary covering service uptime compliance, critical downtime incidents, and automated recovery actions.');

  // Options Toggles
  const [incTable, setIncTable] = React.useState(true);
  const [incCharts, setIncCharts] = React.useState(true);
  const [incAiPostMortem, setIncAiPostMortem] = React.useState(true);
  const [incTimelines, setIncTimelines] = React.useState(true);

  // Export Dialog State
  const [exportModal, setExportModal] = React.useState<{
    open: boolean;
    format: 'md' | 'txt' | 'pdf';
    fileName: string;
  } | null>(null);
  const [openImmediately, setOpenImmediately] = React.useState(true);

  React.useEffect(() => {
    try {
      const storedProfiles = localStorage.getItem('uptime_sentry_profiles');
      const storedTargets = localStorage.getItem('uptime_sentry_targets');
      const activeId = localStorage.getItem('uptime_sentry_active_id');

      if (storedProfiles) {
        const pList = JSON.parse(storedProfiles) as Profile[];
        setProfiles(pList);
        if (activeId && pList.some(p => p.id === activeId)) {
          setSelectedProfileId(activeId);
        } else if (pList.length > 0) {
          setSelectedProfileId(pList[0].id);
        }
      }

      if (storedTargets) {
        setTargets(JSON.parse(storedTargets));
      }
    } catch (e) {
      console.error('Failed to load profiles/targets for reports:', e);
    }
  }, []);

  const activeProfileObj = profiles.find(p => p.id === selectedProfileId);
  const activeTargetsList = targets.filter(t => t.profileId === selectedProfileId);

  const generateMarkdownReport = () => {
    let md = `# ${reportTitle}\n\n`;
    md += `**Generated by:** UptimeSentry Infrastructure Engine (v1.0.0)\n`;
    md += `**Date Range:** ${fromDate} to ${toDate}\n`;
    md += `**Scope:** ${scope === 'profile' ? `Profile: ${activeProfileObj?.name || 'All Profiles'}` : 'Specific Target'}\n\n`;

    if (authorNotes.trim()) {
      md += `## Executive Notes\n${authorNotes}\n\n`;
    }

    if (incTable) {
      md += `## Availability & SLA Summary Metrics\n\n`;
      md += `| Time Period | Availability | Downtime | Incidents | Longest Incident | Avg. Duration |\n`;
      md += `| --- | --- | --- | --- | --- | --- |\n`;
      md += `| Today | 100.0000% | none | 0 | none | none |\n`;
      md += `| Last 7 days | 99.5773% | 42 minutes | 1 | 42 minutes | 42 minutes |\n`;
      md += `| Last 30 days | 99.6851% | 2 hours 15 mins | 3 | 1 hour 8 mins | 45 minutes |\n`;
      md += `| Last 365 days | 97.1724% | 1 week 3 days | 13 | 1 week 1 day | 19 hours |\n\n`;
    }

    if (incAiPostMortem) {
      md += `## Automated Post-Mortem Analysis\n\n`;
      md += `### Incident #104 — Keyword Missing (Cloudflare API)\n`;
      md += `- **Started:** Aug 5, 2026 at 10:03am CEST\n`;
      md += `- **Resolved:** Aug 5, 2026 at 10:45am CEST (42 minutes)\n`;
      md += `- **Root Cause:** Keyword not found (looked for "Pages","status":"operational")\n`;
      md += `- **Post-Mortem Summary:** The monitor flagged the endpoint as down because expected keyword was missing. Endpoint returned HTTP 200. Multi-region checks confirmed missing keyword before auto-recovering.\n\n`;
    }

    if (incTimelines) {
      md += `## Incident Audit Log Timeline\n\n`;
      md += `- **Aug 5 at 10:48am CEST:** Incident resolved automatically.\n`;
      md += `- **Aug 5 at 10:45am CEST:** Monitor recovered in Europe, North America, Australia.\n`;
      md += `- **Aug 5 at 10:04am CEST:** Notifying team. Incident started.\n`;
      md += `- **Aug 5 at 10:03am CEST:** Initial keyword check failure detected.\n\n`;
    }

    md += `---\n*Report generated by UptimeSentry — High-Performance Desktop Monitoring Suite*`;
    return md;
  };

  const triggerOpenExportDialog = (format: 'md' | 'txt' | 'pdf') => {
    const ext = format === 'md' ? 'md' : format === 'txt' ? 'txt' : 'pdf';
    setExportModal({
      open: true,
      format,
      fileName: `UptimeSentry_SLA_Report_${fromDate}_to_${toDate}.${ext}`,
    });
  };

  const handleConfirmSaveExport = async () => {
    if (!exportModal) return;

    if (exportModal.format === 'pdf') {
      setExportModal(null);
      setTimeout(() => {
        window.print();
      }, 300);
      return;
    }

    const content = generateMarkdownReport();
    const ext = exportModal.format === 'md' ? 'md' : 'txt';
    const mimeType = exportModal.format === 'md' ? 'text/markdown' : 'text/plain';

    // Native desktop Save As dialog if supported
    if (typeof (window as unknown as { showSaveFilePicker?: unknown }).showSaveFilePicker === 'function') {
      try {
        const handle = await (window as unknown as { showSaveFilePicker: (opts: unknown) => Promise<{ createWritable(): Promise<{ write(c: string): Promise<void>; close(): Promise<void> }> }> }).showSaveFilePicker({
          suggestedName: exportModal.fileName,
          types: [{
            description: exportModal.format === 'md' ? 'Markdown Document' : 'Plain Text Document',
            accept: { [mimeType]: [`.${ext}`] },
          }],
        });
        const writable = await handle.createWritable();
        await writable.write(content);
        await writable.close();

        if (openImmediately) {
          const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
          const url = URL.createObjectURL(blob);
          window.open(url, '_blank');
        }
        setExportModal(null);
        return;
      } catch (err: unknown) {
        if ((err as { name?: string }).name === 'AbortError') {
          return; // User cancelled file save dialog
        }
      }
    }

    // Fallback browser download
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = exportModal.fileName;
    a.click();

    if (openImmediately) {
      setTimeout(() => window.open(url, '_blank'), 100);
    }

    setTimeout(() => { URL.revokeObjectURL(url); }, 1000);
    setExportModal(null);
  };

  return (
    <Box sx={{ width: '100%', maxWidth: { sm: '100%', md: '1700px' }, userSelect: 'none' }}>
      {/* Print CSS Rules to isolate report document for PDF export */}
      <style>{`
        @media print {
          @page {
            margin: 12mm;
            size: portrait;
          }
          body, html {
            background: #ffffff !important;
            color: #111827 !important;
          }
          .no-print, header, nav, aside, button, .MuiAppBar-root, .MuiDrawer-root, .MuiGrid-grid-md-4 {
            display: none !important;
          }
          .printable-report {
            width: 100% !important;
            max-width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            background: #ffffff !important;
            color: #111827 !important;
            box-shadow: none !important;
            border: none !important;
          }
          .printable-report * {
            color: #111827 !important;
            background: transparent !important;
            border-color: #e5e7eb !important;
          }
        }
      `}</style>

      <Grid container spacing={3}>
        {/* Left Side: Report Options Form */}
        <Grid size={{ xs: 12, md: 4 }} className="no-print">
          <Card variant="outlined">
            <CardContent sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}>
              <Stack direction="row" spacing={1} sx={{ alignItems: 'center', color: 'primary.main' }}>
                <AssessmentIcon />
                <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
                  Generate SLA Report
                </Typography>
              </Stack>
              <Divider />

              <TextField
                label="Report Title"
                size="small"
                fullWidth
                value={reportTitle}
                onChange={(e) => { setReportTitle(e.target.value); }}
              />

              <TextField
                select
                label="Target Scope"
                size="small"
                fullWidth
                value={scope}
                onChange={(e) => { setScope(e.target.value as 'profile' | 'target'); }}
              >
                <MenuItem value="profile">Entire Profile</MenuItem>
                <MenuItem value="target">Specific Target</MenuItem>
              </TextField>

              <TextField
                select
                label="Profile Selection"
                size="small"
                fullWidth
                value={selectedProfileId}
                onChange={(e) => { setSelectedProfileId(e.target.value); }}
              >
                {profiles.map((p) => (
                  <MenuItem key={p.id} value={p.id}>
                    {p.name}
                  </MenuItem>
                ))}
              </TextField>

              {scope === 'target' && (
                <TextField
                  select
                  label="Select Target"
                  size="small"
                  fullWidth
                  value={selectedTargetId}
                  onChange={(e) => { setSelectedTargetId(e.target.value); }}
                >
                  <MenuItem value="all">All Profile Targets</MenuItem>
                  {activeTargetsList.map((t) => (
                    <MenuItem key={t.id} value={t.id}>
                      {t.name}
                    </MenuItem>
                  ))}
                </TextField>
              )}

              <Stack direction="row" spacing={1.5}>
                <TextField
                  type="date"
                  label="From Date"
                  size="small"
                  fullWidth
                  value={fromDate}
                  onChange={(e) => { setFromDate(e.target.value); }}
                  slotProps={{ inputLabel: { shrink: true } }}
                />
                <TextField
                  type="date"
                  label="To Date"
                  size="small"
                  fullWidth
                  value={toDate}
                  onChange={(e) => { setToDate(e.target.value); }}
                  slotProps={{ inputLabel: { shrink: true } }}
                />
              </Stack>

              <TextField
                label="Executive Notes / Comments"
                multiline
                minRows={4}
                size="small"
                fullWidth
                value={authorNotes}
                onChange={(e) => { setAuthorNotes(e.target.value); }}
                slotProps={{ inputLabel: { shrink: true } }}
                sx={{
                  '& .MuiInputBase-root': { py: 1.5, px: 1.5, lineHeight: 1.5 },
                }}
              />

              <Divider />
              <Typography variant="subtitle2" sx={{ fontWeight: 'bold' }}>
                Report Contents & Visuals
              </Typography>
              <Stack spacing={0.5}>
                <FormControlLabel
                  control={<Checkbox checked={incTable} onChange={(e) => { setIncTable(e.target.checked); }} size="small" />}
                  label="Include SLA Availability Summary Table"
                />
                <FormControlLabel
                  control={<Checkbox checked={incCharts} onChange={(e) => { setIncCharts(e.target.checked); }} size="small" />}
                  label="Include Latency Charts & Visuals"
                />
                <FormControlLabel
                  control={<Checkbox checked={incAiPostMortem} onChange={(e) => { setIncAiPostMortem(e.target.checked); }} size="small" />}
                  label="Include Post-Mortem Outage Summaries"
                />
                <FormControlLabel
                  control={<Checkbox checked={incTimelines} onChange={(e) => { setIncTimelines(e.target.checked); }} size="small" />}
                  label="Include Incident Audit Log Timelines"
                />
              </Stack>

              <Divider />
              <Typography variant="subtitle2" sx={{ fontWeight: 'bold' }}>
                Export Options
              </Typography>
              <Stack spacing={1}>
                <Button variant="contained" startIcon={<DownloadIcon />} onClick={() => { triggerOpenExportDialog('md'); }}>
                  Export Markdown (.md)
                </Button>
                <Button variant="outlined" startIcon={<DescriptionIcon />} onClick={() => { triggerOpenExportDialog('txt'); }}>
                  Export Plain Text (.txt)
                </Button>
                <Button variant="outlined" color="secondary" startIcon={<PrintIcon />} onClick={() => { triggerOpenExportDialog('pdf'); }}>
                  Export / Print PDF (.pdf)
                </Button>
              </Stack>
            </CardContent>
          </Card>
        </Grid>

        {/* Right Side: Live Report Document Preview */}
        <Grid size={{ xs: 12, md: 8 }} className="printable-report">
          <Card variant="outlined" sx={{ bgcolor: 'background.paper', p: 3, userSelect: 'text' }}>
            <Box sx={{ borderBottom: '2px solid', borderColor: 'primary.main', pb: 2, mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Box>
                <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 'bold', letterSpacing: 1 }}>
                  UPTIMESENTRY INFRASTRUCTURE REPORT
                </Typography>
                <Typography variant="h5" sx={{ fontWeight: 'bold', color: 'primary.main' }}>
                  {reportTitle}
                </Typography>
                <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
                  Scope: {activeProfileObj?.name || 'All Targets'} • Date Range: {fromDate} to {toDate}
                </Typography>
              </Box>
              <Chip label="SLA REPORT" color="primary" variant="outlined" size="small" />
            </Box>

            {authorNotes && (
              <Box sx={{ mb: 3, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 0.5 }}>
                  Executive Notes
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6 }}>
                  {authorNotes}
                </Typography>
              </Box>
            )}

            {incTable && (
              <Box sx={{ mb: 3 }}>
                <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1 }}>
                  Availability & Uptime Summary Table
                </Typography>
                <TableContainer component={Paper} variant="outlined">
                  <Table size="small">
                    <TableHead sx={{ bgcolor: 'action.hover' }}>
                      <TableRow>
                        <TableCell sx={{ fontWeight: 'bold' }}>Time Period</TableCell>
                        <TableCell sx={{ fontWeight: 'bold' }}>Availability</TableCell>
                        <TableCell sx={{ fontWeight: 'bold' }}>Downtime</TableCell>
                        <TableCell sx={{ fontWeight: 'bold' }}>Incidents</TableCell>
                        <TableCell sx={{ fontWeight: 'bold' }}>Longest Incident</TableCell>
                        <TableCell sx={{ fontWeight: 'bold' }}>Avg. Incident</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      <TableRow>
                        <TableCell>Today</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'success.main' }}>100.0000%</TableCell>
                        <TableCell>none</TableCell>
                        <TableCell>0</TableCell>
                        <TableCell>none</TableCell>
                        <TableCell>none</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Last 7 days</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'success.main' }}>99.5773%</TableCell>
                        <TableCell>42 minutes</TableCell>
                        <TableCell>1</TableCell>
                        <TableCell>42 minutes</TableCell>
                        <TableCell>42 minutes</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Last 30 days</TableCell>
                        <TableCell sx={{ fontWeight: 'bold', color: 'success.main' }}>99.6851%</TableCell>
                        <TableCell>2 hours and 15 minutes</TableCell>
                        <TableCell>3</TableCell>
                        <TableCell>1 hour and 8 minutes</TableCell>
                        <TableCell>45 minutes</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>
              </Box>
            )}

            {incAiPostMortem && (
              <Box sx={{ mb: 3 }}>
                <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1 }}>
                  Automated Incident Post-Mortem Summary
                </Typography>
                <Box sx={{ p: 2, border: '1px solid', borderColor: 'divider', borderRadius: 1 }}>
                  <Stack direction="row" sx={{ justifyContent: 'space-between', mb: 1 }}>
                    <Typography variant="body2" sx={{ fontWeight: 'bold' }}>
                      Incident #104 — Keyword Missing (Cloudflare API)
                    </Typography>
                    <Chip label="Resolved (42m)" size="small" color="success" />
                  </Stack>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
                    Root Cause: Keyword not found (looked for "Pages","status":"operational")
                  </Typography>
                  <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6 }}>
                    The monitor flagged the Cloudflare status summary as down because the expected keyword was not found in the JSON response, even though the endpoint returned HTTP 200. Multi-region checks confirmed missing keyword before auto-recovering.
                  </Typography>
                </Box>
              </Box>
            )}

            {incTimelines && (
              <Box sx={{ mb: 3 }}>
                <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1 }}>
                  Audit Lifecycle Timeline
                </Typography>
                <Stack spacing={1} sx={{ pl: 2, borderLeft: '2px solid', borderColor: 'primary.main' }}>
                  <Box sx={{ py: 0.5 }}>
                    <Typography variant="caption" sx={{ fontWeight: 'bold' }}>Aug 5 at 10:48am CEST</Typography>
                    <Typography variant="body2">Incident resolved automatically.</Typography>
                  </Box>
                  <Box sx={{ py: 0.5 }}>
                    <Typography variant="caption" sx={{ fontWeight: 'bold' }}>Aug 5 at 10:45am CEST</Typography>
                    <Typography variant="body2">Monitor recovered in Europe, North America, Australia.</Typography>
                  </Box>
                  <Box sx={{ py: 0.5 }}>
                    <Typography variant="caption" sx={{ fontWeight: 'bold' }}>Aug 5 at 10:04am CEST</Typography>
                    <Typography variant="body2">Incident started. Notifying team.</Typography>
                  </Box>
                </Stack>
              </Box>
            )}

            <Divider sx={{ my: 3 }} />
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="caption" color="text.secondary">
                Report generated via UptimeSentry Desktop SLA Suite v1.0.0
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Page 1 of 1
              </Typography>
            </Box>
          </Card>
        </Grid>
      </Grid>

      {/* Export Confirmation & Options Modal */}
      {exportModal && (
        <Dialog
          open={exportModal.open}
          onClose={() => { setExportModal(null); }}
          maxWidth="xs"
          fullWidth
          slotProps={{
            paper: {
              sx: {
                bgcolor: 'background.paper',
                color: 'text.primary',
                backgroundImage: 'none',
                border: '1px solid',
                borderColor: 'divider',
              }
            }
          }}
        >
          <DialogTitle sx={{ fontWeight: 'bold' }}>
            Save SLA Report ({exportModal.format.toUpperCase()})
          </DialogTitle>
          <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
            <TextField
              label="File Name"
              size="small"
              fullWidth
              value={exportModal.fileName}
              onChange={(e) => { setExportModal({ ...exportModal, fileName: e.target.value }); }}
              sx={{
                mt: 1,
                '& .MuiInputBase-root': { bgcolor: 'action.hover' }
              }}
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={openImmediately}
                  onChange={(e) => { setOpenImmediately(e.target.checked); }}
                  color="primary"
                />
              }
              label="Open file immediately after saving"
            />
          </DialogContent>
          <DialogActions sx={{ p: 2 }}>
            <Button variant="outlined" onClick={() => { setExportModal(null); }}>
              Cancel
            </Button>
            <Button variant="contained" startIcon={<DownloadIcon />} onClick={handleConfirmSaveExport}>
              Save & Export
            </Button>
          </DialogActions>
        </Dialog>
      )}
    </Box>
  );
}
